name: CI for Next.js with Docker and SonarCloud

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Create credential.json file
      run: echo "${{ secrets.CREDENTIAL_JSON }}" > ./credential.json

    - name: Run tests
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/credential.json
      run: |
        npm test > /home/runner/test.log
        cat /home/runner/test.log

#    - name: SonarCloud Scan
#      uses: SonarSource/sonarcloud-github-action@v1.5
#      with:
#        args: >
#          -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
#          -Dsonar.organization=<YOUR_ORGANIZATION>
#          -Dsonar.host.url=https://sonarcloud.io
#          -Dsonar.login=${{ secrets.SONAR_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/easyaccountbooking-app:latest


  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm test

